version: '3'
services:
  truffle:
    build:
      context: ./docker
      dockerfile: truffle
    image: truffle:latest
    container_name: truffle
    links:
      - ganache
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    command: ["--host", "0.0.0.0"]
    environment:
      - DOCKER=true

